easy_admin:
    entities:
        IllustrationArticle:
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        Image:
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.galerie_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.galerie_images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        Postulant:
            list:
                fields:
                    - { property: 'cv', base_path: '%app.path.cv_pdf%' }
            form:
                fields:
                    - { property: 'cvFile', type: 'vich_file' }